# This is a main workflow which will run if there is a change in the theme
name: ProdComplete

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Dispatch Events
      uses: peter-evans/repository-dispatch@v1
      with:
          token:  ${{ secrets.ASPOSE_REPO_CI }}
          repository: Aspose/releases.aspose.com
          event-type: prod-complete
