# This is a basic workflow to help you get started with Actions

name: prod-finance

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the mentioned branches
  push:
    branches: [ main ]
    paths:
      - 'content/de/finance/**'
      - 'content/el/finance/**'
      - 'content/en/finance/**'
      - 'content/es/finance/**'
      - 'content/fr/finance/**'
      - 'content/id/finance/**'
      - 'content/ja/finance/**'
      - 'content/pt/finance/**'
      - 'content/ru/finance/**'
      - 'content/tr/finance/**'
      - 'content/zh/finance/**'

  # Allows the workflow run manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: '0.101.0'

    - name: Remove unwanted folders
      run: |

        if [ -d "./content/de" ]; then
        find ./content/de -mindepth 1 ! -regex '^./content/de/finance\(/.*\)?' -delete
        fi
        if [ -d "./content/el" ]; then
        find ./content/el -mindepth 1 ! -regex '^./content/el/finance\(/.*\)?' -delete
        fi
        if [ -d "./content/en" ]; then
        find ./content/en -mindepth 1 ! -regex '^./content/en/finance\(/.*\)?' -delete
        fi
        if [ -d "./content/es" ]; then
        find ./content/es -mindepth 1 ! -regex '^./content/es/finance\(/.*\)?' -delete
        fi
        if [ -d "./content/fr" ]; then
        find ./content/fr -mindepth 1 ! -regex '^./content/fr/finance\(/.*\)?' -delete
        fi
        if [ -d "./content/id" ]; then
        find ./content/id -mindepth 1 ! -regex '^./content/id/finance\(/.*\)?' -delete
        fi
        if [ -d "./content/ja" ]; then
        find ./content/ja -mindepth 1 ! -regex '^./content/ja/finance\(/.*\)?' -delete
        fi
        if [ -d "./content/pt" ]; then
        find ./content/pt -mindepth 1 ! -regex '^./content/pt/finance\(/.*\)?' -delete
        fi
        if [ -d "./content/ru" ]; then
        find ./content/ru -mindepth 1 ! -regex '^./content/ru/finance\(/.*\)?' -delete
        fi
        if [ -d "./content/tr" ]; then
        find ./content/tr -mindepth 1 ! -regex '^./content/tr/finance\(/.*\)?' -delete
        fi
        if [ -d "./content/zh" ]; then
        find ./content/zh -mindepth 1 ! -regex '^./content/zh/finance\(/.*\)?' -delete
        fi
        rm ./layouts/sitemap.xml;
        ls content/ -all;

    - name: Build finance pages
      run: hugo --config "./config/config-prod-releases-aspose-com.toml"  -b "https://releases.aspose.com/" --disableKinds=taxonomy,category --cleanDestinationDir --minify

    - name: Prepare public folder
      run: |

        mv public/de/sitemap.xml public/de/sitemap-finance.xml;
        mv public/el/sitemap.xml public/el/sitemap-finance.xml;
        mv public/en/sitemap.xml public/en/sitemap-finance.xml;
        mv public/es/sitemap.xml public/es/sitemap-finance.xml;
        mv public/fr/sitemap.xml public/fr/sitemap-finance.xml;
        mv public/id/sitemap.xml public/id/sitemap-finance.xml;
        mv public/ja/sitemap.xml public/ja/sitemap-finance.xml;
        mv public/pt/sitemap.xml public/pt/sitemap-finance.xml;
        mv public/ru/sitemap.xml public/ru/sitemap-finance.xml;
        mv public/tr/sitemap.xml public/tr/sitemap-finance.xml;
        mv public/zh/sitemap.xml public/zh/sitemap-finance.xml;

        rm public/index.html;
        rm public/index.json;
        ls public -all;

    - name: Upload finance sitemap index
      uses: zdurham/s3-upload-github-action@master
      with:
        args: --acl public-read
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        S3_BUCKET: 'releases.aspose.com'
        FILE: 'public/sitemap.xml'
        AWS_REGION: 'us-west-2'
        S3_KEY: 'sitemap.xml'

    - name: Upload default language folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/finance'
        DEST_DIR: 'finance'

    - name: Upload en sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/en/sitemap-finance.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'en/'

    - name: Upload de folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/de/finance'
        DEST_DIR: 'de/finance'

    - name: Upload de sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/de/sitemap-finance.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'de/'

    - name: Upload el folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/el/finance'
        DEST_DIR: 'el/finance'

    - name: Upload el sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/el/sitemap-finance.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'el/'

    - name: Upload es folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/es/finance'
        DEST_DIR: 'es/finance'

    - name: Upload es sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/es/sitemap-finance.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'es/'

    - name: Upload fr folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/fr/finance'
        DEST_DIR: 'fr/finance'

    - name: Upload fr sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/fr/sitemap-finance.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'fr/'

    - name: Upload id folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/id/finance'
        DEST_DIR: 'id/finance'

    - name: Upload id sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/id/sitemap-finance.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'id/'

    - name: Upload ja folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/ja/finance'
        DEST_DIR: 'ja/finance'

    - name: Upload ja sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/ja/sitemap-finance.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'ja/'

    - name: Upload pt folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/pt/finance'
        DEST_DIR: 'pt/finance'

    - name: Upload pt sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/pt/sitemap-finance.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'pt/'

    - name: Upload ru folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/ru/finance'
        DEST_DIR: 'ru/finance'

    - name: Upload ru sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/ru/sitemap-finance.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'ru/'

    - name: Upload tr folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/tr/finance'
        DEST_DIR: 'tr/finance'

    - name: Upload tr sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/tr/sitemap-finance.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'tr/'

    - name: Upload zh folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/zh/finance'
        DEST_DIR: 'zh/finance'

    - name: Upload zh sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/zh/sitemap-finance.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'zh/'

    # Invalidate Cloudfront (this action)
    - name: invalidate
      continue-on-error: true
      uses: chetan/invalidate-cloudfront-action@master
      env:
        DISTRIBUTION: ${{ secrets.AWS_DISTRIBUTION_PROD }}
        PATHS: / /index.html /index.json /sitemap.xml /de/sitemap-finance.xml /el/sitemap-finance.xml /en/sitemap-finance.xml /es/sitemap-finance.xml /fr/sitemap-finance.xml /id/sitemap-finance.xml /ja/sitemap-finance.xml /pt/sitemap-finance.xml /ru/sitemap-finance.xml /tr/sitemap-finance.xml /zh/sitemap-finance.xml /finance/* /de/finance/* /el/finance/* /en/finance/* /es/finance/* /fr/finance/* /id/finance/* /ja/finance/* /pt/finance/* /ru/finance/* /tr/finance/* /zh/finance/*
        AWS_REGION: 'us-west-2'
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}
