# This is a basic workflow to help you get started with Actions

name: prod-pdf

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the mentioned branches
  push:
    branches: [ main ]
    paths:
      - 'content/de/pdf/**'
      - 'content/el/pdf/**'
      - 'content/en/pdf/**'
      - 'content/es/pdf/**'
      - 'content/fr/pdf/**'
      - 'content/id/pdf/**'
      - 'content/ja/pdf/**'
      - 'content/pt/pdf/**'
      - 'content/ru/pdf/**'
      - 'content/tr/pdf/**'
      - 'content/zh/pdf/**'

  # Allows the workflow run manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: '0.101.0'

    - name: Remove unwanted folders
      run: |

        if [ -d "./content/de" ]; then
        find ./content/de -mindepth 1 ! -regex '^./content/de/pdf\(/.*\)?' -delete
        fi
        if [ -d "./content/el" ]; then
        find ./content/el -mindepth 1 ! -regex '^./content/el/pdf\(/.*\)?' -delete
        fi
        if [ -d "./content/en" ]; then
        find ./content/en -mindepth 1 ! -regex '^./content/en/pdf\(/.*\)?' -delete
        fi
        if [ -d "./content/es" ]; then
        find ./content/es -mindepth 1 ! -regex '^./content/es/pdf\(/.*\)?' -delete
        fi
        if [ -d "./content/fr" ]; then
        find ./content/fr -mindepth 1 ! -regex '^./content/fr/pdf\(/.*\)?' -delete
        fi
        if [ -d "./content/id" ]; then
        find ./content/id -mindepth 1 ! -regex '^./content/id/pdf\(/.*\)?' -delete
        fi
        if [ -d "./content/ja" ]; then
        find ./content/ja -mindepth 1 ! -regex '^./content/ja/pdf\(/.*\)?' -delete
        fi
        if [ -d "./content/pt" ]; then
        find ./content/pt -mindepth 1 ! -regex '^./content/pt/pdf\(/.*\)?' -delete
        fi
        if [ -d "./content/ru" ]; then
        find ./content/ru -mindepth 1 ! -regex '^./content/ru/pdf\(/.*\)?' -delete
        fi
        if [ -d "./content/tr" ]; then
        find ./content/tr -mindepth 1 ! -regex '^./content/tr/pdf\(/.*\)?' -delete
        fi
        if [ -d "./content/zh" ]; then
        find ./content/zh -mindepth 1 ! -regex '^./content/zh/pdf\(/.*\)?' -delete
        fi

        ls content/ -all;

    - name: Build pdf pages
      run: hugo --config "./config/config-prod-releases-aspose-com.toml"  -b "https://releases.aspose.com/" --disableKinds=taxonomy,category --cleanDestinationDir --minify

    - name: Prepare public folder
      run: |

        mv public/de/sitemap.xml public/de/sitemap-pdf.xml;
        mv public/el/sitemap.xml public/el/sitemap-pdf.xml;
        mv public/en/sitemap.xml public/en/sitemap-pdf.xml;
        mv public/es/sitemap.xml public/es/sitemap-pdf.xml;
        mv public/fr/sitemap.xml public/fr/sitemap-pdf.xml;
        mv public/id/sitemap.xml public/id/sitemap-pdf.xml;
        mv public/ja/sitemap.xml public/ja/sitemap-pdf.xml;
        mv public/pt/sitemap.xml public/pt/sitemap-pdf.xml;
        mv public/ru/sitemap.xml public/ru/sitemap-pdf.xml;
        mv public/tr/sitemap.xml public/tr/sitemap-pdf.xml;
        mv public/zh/sitemap.xml public/zh/sitemap-pdf.xml;

        rm public/index.html;
        rm public/index.json;
        ls public -all;

    - name: Upload pdf sitemap index
      uses: zdurham/s3-upload-github-action@master
      with:
        args: --acl public-read
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        S3_BUCKET: 'releases.aspose.com'
        FILE: 'public/sitemap.xml'
        AWS_REGION: 'us-west-2'
        S3_KEY: 'sitemap.xml'

    - name: Upload default language folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/pdf'
        DEST_DIR: 'pdf'

    - name: Upload en sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/en/sitemap-pdf.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'en/'

    - name: Upload de folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/de/pdf'
        DEST_DIR: 'de/pdf'

    - name: Upload de sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/de/sitemap-pdf.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'de/'

    - name: Upload el folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/el/pdf'
        DEST_DIR: 'el/pdf'

    - name: Upload el sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/el/sitemap-pdf.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'el/'

    - name: Upload es folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/es/pdf'
        DEST_DIR: 'es/pdf'

    - name: Upload es sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/es/sitemap-pdf.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'es/'

    - name: Upload fr folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/fr/pdf'
        DEST_DIR: 'fr/pdf'

    - name: Upload fr sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/fr/sitemap-pdf.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'fr/'

    - name: Upload id folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/id/pdf'
        DEST_DIR: 'id/pdf'

    - name: Upload id sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/id/sitemap-pdf.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'id/'

    - name: Upload ja folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/ja/pdf'
        DEST_DIR: 'ja/pdf'

    - name: Upload ja sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/ja/sitemap-pdf.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'ja/'

    - name: Upload pt folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/pt/pdf'
        DEST_DIR: 'pt/pdf'

    - name: Upload pt sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/pt/sitemap-pdf.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'pt/'

    - name: Upload ru folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/ru/pdf'
        DEST_DIR: 'ru/pdf'

    - name: Upload ru sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/ru/sitemap-pdf.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'ru/'

    - name: Upload tr folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/tr/pdf'
        DEST_DIR: 'tr/pdf'

    - name: Upload tr sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/tr/sitemap-pdf.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'tr/'

    - name: Upload zh folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/zh/pdf'
        DEST_DIR: 'zh/pdf'

    - name: Upload zh sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/zh/sitemap-pdf.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'zh/'

    # Invalidate Cloudfront (this action)
    - name: invalidate
      uses: chetan/invalidate-cloudfront-action@master
      env:
        DISTRIBUTION: ${{ secrets.AWS_DISTRIBUTION_PROD }}
        PATHS: / /index.html /index.json /sitemap.xml /de/sitemap-pdf.xml /el/sitemap-pdf.xml /en/sitemap-pdf.xml /es/sitemap-pdf.xml /fr/sitemap-pdf.xml /id/sitemap-pdf.xml /ja/sitemap-pdf.xml /pt/sitemap-pdf.xml /ru/sitemap-pdf.xml /tr/sitemap-pdf.xml /zh/sitemap-pdf.xml /pdf/* /de/pdf/* /el/pdf/* /en/pdf/* /es/pdf/* /fr/pdf/* /id/pdf/* /ja/pdf/* /pt/pdf/* /ru/pdf/* /tr/pdf/* /zh/pdf/*
        AWS_REGION: 'us-west-2'
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}
