# This is a basic workflow to help you get started with Actions

name: prod-3d

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the mentioned branches
  push:
    branches: [ main ]
    paths:
      - 'content/de/3d/**'
      - 'content/el/3d/**'
      - 'content/en/3d/**'
      - 'content/es/3d/**'
      - 'content/fr/3d/**'
      - 'content/id/3d/**'
      - 'content/ja/3d/**'
      - 'content/pt/3d/**'
      - 'content/ru/3d/**'
      - 'content/tr/3d/**'
      - 'content/zh/3d/**'

  # Allows the workflow run manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: '0.101.0'

    - name: Remove unwanted folders
      run: |

        if [ -d "./content/de" ]; then
        find ./content/de -mindepth 1 ! -regex '^./content/de/3d\(/.*\)?' -delete
        fi
        if [ -d "./content/el" ]; then
        find ./content/el -mindepth 1 ! -regex '^./content/el/3d\(/.*\)?' -delete
        fi
        if [ -d "./content/en" ]; then
        find ./content/en -mindepth 1 ! -regex '^./content/en/3d\(/.*\)?' -delete
        fi
        if [ -d "./content/es" ]; then
        find ./content/es -mindepth 1 ! -regex '^./content/es/3d\(/.*\)?' -delete
        fi
        if [ -d "./content/fr" ]; then
        find ./content/fr -mindepth 1 ! -regex '^./content/fr/3d\(/.*\)?' -delete
        fi
        if [ -d "./content/id" ]; then
        find ./content/id -mindepth 1 ! -regex '^./content/id/3d\(/.*\)?' -delete
        fi
        if [ -d "./content/ja" ]; then
        find ./content/ja -mindepth 1 ! -regex '^./content/ja/3d\(/.*\)?' -delete
        fi
        if [ -d "./content/pt" ]; then
        find ./content/pt -mindepth 1 ! -regex '^./content/pt/3d\(/.*\)?' -delete
        fi
        if [ -d "./content/ru" ]; then
        find ./content/ru -mindepth 1 ! -regex '^./content/ru/3d\(/.*\)?' -delete
        fi
        if [ -d "./content/tr" ]; then
        find ./content/tr -mindepth 1 ! -regex '^./content/tr/3d\(/.*\)?' -delete
        fi
        if [ -d "./content/zh" ]; then
        find ./content/zh -mindepth 1 ! -regex '^./content/zh/3d\(/.*\)?' -delete
        fi

        ls content/ -all;

    - name: Build 3d pages
      run: hugo --config "./config/config-prod-releases-aspose-com.toml"  -b "https://releases.aspose.com/" --disableKinds=taxonomy,category --cleanDestinationDir --minify

    - name: Prepare public folder
      run: |

        mv public/de/sitemap.xml public/de/sitemap-3d.xml;
        mv public/el/sitemap.xml public/el/sitemap-3d.xml;
        mv public/en/sitemap.xml public/en/sitemap-3d.xml;
        mv public/es/sitemap.xml public/es/sitemap-3d.xml;
        mv public/fr/sitemap.xml public/fr/sitemap-3d.xml;
        mv public/id/sitemap.xml public/id/sitemap-3d.xml;
        mv public/ja/sitemap.xml public/ja/sitemap-3d.xml;
        mv public/pt/sitemap.xml public/pt/sitemap-3d.xml;
        mv public/ru/sitemap.xml public/ru/sitemap-3d.xml;
        mv public/tr/sitemap.xml public/tr/sitemap-3d.xml;
        mv public/zh/sitemap.xml public/zh/sitemap-3d.xml;

        rm public/index.html;
        rm public/index.json;
        ls public -all;

    - name: Upload 3d sitemap index
      uses: zdurham/s3-upload-github-action@master
      with:
        args: --acl public-read
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        S3_BUCKET: 'releases.aspose.com'
        FILE: 'public/sitemap.xml'
        AWS_REGION: 'us-west-2'
        S3_KEY: 'sitemap.xml'

    - name: Upload default language folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/3d'
        DEST_DIR: '3d'

    - name: Upload en sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/en/sitemap-3d.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'en/'

    - name: Upload de folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/de/3d'
        DEST_DIR: 'de/3d'

    - name: Upload de sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/de/sitemap-3d.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'de/'

    - name: Upload el folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/el/3d'
        DEST_DIR: 'el/3d'

    - name: Upload el sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/el/sitemap-3d.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'el/'

    - name: Upload es folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/es/3d'
        DEST_DIR: 'es/3d'

    - name: Upload es sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/es/sitemap-3d.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'es/'

    - name: Upload fr folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/fr/3d'
        DEST_DIR: 'fr/3d'

    - name: Upload fr sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/fr/sitemap-3d.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'fr/'

    - name: Upload id folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/id/3d'
        DEST_DIR: 'id/3d'

    - name: Upload id sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/id/sitemap-3d.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'id/'

    - name: Upload ja folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/ja/3d'
        DEST_DIR: 'ja/3d'

    - name: Upload ja sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/ja/sitemap-3d.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'ja/'

    - name: Upload pt folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/pt/3d'
        DEST_DIR: 'pt/3d'

    - name: Upload pt sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/pt/sitemap-3d.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'pt/'

    - name: Upload ru folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/ru/3d'
        DEST_DIR: 'ru/3d'

    - name: Upload ru sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/ru/sitemap-3d.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'ru/'

    - name: Upload tr folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/tr/3d'
        DEST_DIR: 'tr/3d'

    - name: Upload tr sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/tr/sitemap-3d.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'tr/'

    - name: Upload zh folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/zh/3d'
        DEST_DIR: 'zh/3d'

    - name: Upload zh sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/zh/sitemap-3d.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'zh/'

    # Invalidate Cloudfront (this action)
    - name: invalidate
      continue-on-error: true
      uses: chetan/invalidate-cloudfront-action@master
      env:
        DISTRIBUTION: ${{ secrets.AWS_DISTRIBUTION_PROD }}
        PATHS: / /index.html /index.json /sitemap.xml /de/sitemap-3d.xml /el/sitemap-3d.xml /en/sitemap-3d.xml /es/sitemap-3d.xml /fr/sitemap-3d.xml /id/sitemap-3d.xml /ja/sitemap-3d.xml /pt/sitemap-3d.xml /ru/sitemap-3d.xml /tr/sitemap-3d.xml /zh/sitemap-3d.xml /3d/* /de/3d/* /el/3d/* /en/3d/* /es/3d/* /fr/3d/* /id/3d/* /ja/3d/* /pt/3d/* /ru/3d/* /tr/3d/* /zh/3d/*
        AWS_REGION: 'us-west-2'
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}
