# This is a basic workflow to help you get started with Actions

name: prod-omr

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the mentioned branches
  push:
    branches: [ main ]
    paths:
      - 'content/de/omr/**'
      - 'content/el/omr/**'
      - 'content/en/omr/**'
      - 'content/es/omr/**'
      - 'content/fr/omr/**'
      - 'content/id/omr/**'
      - 'content/ja/omr/**'
      - 'content/pt/omr/**'
      - 'content/ru/omr/**'
      - 'content/tr/omr/**'
      - 'content/zh/omr/**'

  # Allows the workflow run manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: '0.101.0'

    - name: Remove unwanted folders
      run: |

        if [ -d "./content/de" ]; then
        find ./content/de -mindepth 1 ! -regex '^./content/de/omr\(/.*\)?' -delete
        fi
        if [ -d "./content/el" ]; then
        find ./content/el -mindepth 1 ! -regex '^./content/el/omr\(/.*\)?' -delete
        fi
        if [ -d "./content/en" ]; then
        find ./content/en -mindepth 1 ! -regex '^./content/en/omr\(/.*\)?' -delete
        fi
        if [ -d "./content/es" ]; then
        find ./content/es -mindepth 1 ! -regex '^./content/es/omr\(/.*\)?' -delete
        fi
        if [ -d "./content/fr" ]; then
        find ./content/fr -mindepth 1 ! -regex '^./content/fr/omr\(/.*\)?' -delete
        fi
        if [ -d "./content/id" ]; then
        find ./content/id -mindepth 1 ! -regex '^./content/id/omr\(/.*\)?' -delete
        fi
        if [ -d "./content/ja" ]; then
        find ./content/ja -mindepth 1 ! -regex '^./content/ja/omr\(/.*\)?' -delete
        fi
        if [ -d "./content/pt" ]; then
        find ./content/pt -mindepth 1 ! -regex '^./content/pt/omr\(/.*\)?' -delete
        fi
        if [ -d "./content/ru" ]; then
        find ./content/ru -mindepth 1 ! -regex '^./content/ru/omr\(/.*\)?' -delete
        fi
        if [ -d "./content/tr" ]; then
        find ./content/tr -mindepth 1 ! -regex '^./content/tr/omr\(/.*\)?' -delete
        fi
        if [ -d "./content/zh" ]; then
        find ./content/zh -mindepth 1 ! -regex '^./content/zh/omr\(/.*\)?' -delete
        fi

        ls content/ -all;

    - name: Build omr pages
      run: hugo --config "./config/config-prod-releases-aspose-com.toml"  -b "https://releases.aspose.com/" --disableKinds=taxonomy,category --cleanDestinationDir --minify

    - name: Prepare public folder
      run: |

        mv public/de/sitemap.xml public/de/sitemap-omr.xml;
        mv public/el/sitemap.xml public/el/sitemap-omr.xml;
        mv public/en/sitemap.xml public/en/sitemap-omr.xml;
        mv public/es/sitemap.xml public/es/sitemap-omr.xml;
        mv public/fr/sitemap.xml public/fr/sitemap-omr.xml;
        mv public/id/sitemap.xml public/id/sitemap-omr.xml;
        mv public/ja/sitemap.xml public/ja/sitemap-omr.xml;
        mv public/pt/sitemap.xml public/pt/sitemap-omr.xml;
        mv public/ru/sitemap.xml public/ru/sitemap-omr.xml;
        mv public/tr/sitemap.xml public/tr/sitemap-omr.xml;
        mv public/zh/sitemap.xml public/zh/sitemap-omr.xml;

        rm public/index.html;
        rm public/index.json;
        ls public -all;

    - name: Upload omr sitemap index
      uses: zdurham/s3-upload-github-action@master
      with:
        args: --acl public-read
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        S3_BUCKET: 'releases.aspose.com'
        FILE: 'public/sitemap.xml'
        AWS_REGION: 'us-west-2'
        S3_KEY: 'sitemap.xml'

    - name: Upload default language folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/omr'
        DEST_DIR: 'omr'

    - name: Upload en sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/en/sitemap-omr.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'en/'

    - name: Upload de folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/de/omr'
        DEST_DIR: 'de/omr'

    - name: Upload de sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/de/sitemap-omr.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'de/'

    - name: Upload el folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/el/omr'
        DEST_DIR: 'el/omr'

    - name: Upload el sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/el/sitemap-omr.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'el/'

    - name: Upload es folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/es/omr'
        DEST_DIR: 'es/omr'

    - name: Upload es sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/es/sitemap-omr.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'es/'

    - name: Upload fr folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/fr/omr'
        DEST_DIR: 'fr/omr'

    - name: Upload fr sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/fr/sitemap-omr.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'fr/'

    - name: Upload id folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/id/omr'
        DEST_DIR: 'id/omr'

    - name: Upload id sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/id/sitemap-omr.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'id/'

    - name: Upload ja folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/ja/omr'
        DEST_DIR: 'ja/omr'

    - name: Upload ja sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/ja/sitemap-omr.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'ja/'

    - name: Upload pt folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/pt/omr'
        DEST_DIR: 'pt/omr'

    - name: Upload pt sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/pt/sitemap-omr.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'pt/'

    - name: Upload ru folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/ru/omr'
        DEST_DIR: 'ru/omr'

    - name: Upload ru sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/ru/sitemap-omr.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'ru/'

    - name: Upload tr folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/tr/omr'
        DEST_DIR: 'tr/omr'

    - name: Upload tr sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/tr/sitemap-omr.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'tr/'

    - name: Upload zh folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/zh/omr'
        DEST_DIR: 'zh/omr'

    - name: Upload zh sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases.aspose.com'
        file_path: 'public/zh/sitemap-omr.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'zh/'

    # Invalidate Cloudfront (this action)
    - name: invalidate
      continue-on-error: true    
      uses: chetan/invalidate-cloudfront-action@master
      env:
        DISTRIBUTION: ${{ secrets.AWS_DISTRIBUTION_PROD }}
        PATHS: / /index.html /index.json /sitemap.xml /de/sitemap-omr.xml /el/sitemap-omr.xml /en/sitemap-omr.xml /es/sitemap-omr.xml /fr/sitemap-omr.xml /id/sitemap-omr.xml /ja/sitemap-omr.xml /pt/sitemap-omr.xml /ru/sitemap-omr.xml /tr/sitemap-omr.xml /zh/sitemap-omr.xml /omr/* /de/omr/* /el/omr/* /en/omr/* /es/omr/* /fr/omr/* /id/omr/* /ja/omr/* /pt/omr/* /ru/omr/* /tr/omr/* /zh/omr/*
        AWS_REGION: 'us-west-2'
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}
