# This is a main workflow which will run if there is a change in the theme
name: StagingComplete

on:
  # Triggers the workflow on push or pull request events but only for the main branch and in theme folder
  push:
    branches: [ stage-001 ]
    paths:
      - 'themes/downloads-common-theme/**'
  pull_request:
    branches: [ stage-001 ]
    paths:
      - 'themes/downloads-common-theme/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Dispatch Events
      uses: peter-evans/repository-dispatch@v1
      with:
          token:  ${{ secrets.REPO_TOKEN }}
          event-type: staging-complete
